import Head from 'next/head'
import { useRouter } from 'next/router'
import { useForm } from 'react-hook-form'

const normalInput =
  'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

const errorInput =
  'bg-red-50 border border-red-500 text-red-900 placeholder-red-700 text-sm rounded-lg focus:ring-red-500 dark:bg-gray-700 focus:border-red-500 block w-full p-2.5 dark:text-red-500 dark:placeholder-red-500 dark:border-red-500'

export default function Home() {
  const router = useRouter()

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm({
    mode: 'onTouched',
    reValidateMode: 'onChange',
    defaultValues: {},
    resolver: undefined,
    context: undefined,
    criteriaMode: 'firstError',
    shouldFocusError: true,
    shouldUnregister: false,
    shouldUseNativeValidation: false,
    delayError: undefined,
  })
  const onSubmit = (data) => router.push('/crud')

  return (
    <section className='bg-gray-50 dark:bg-gray-900'>
      <Head>
        <title>React Samples</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0'>
        <a
          href='#'
          className='flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white'
        >
          <img
            className='w-8 h-8 mr-2'
            src='https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg'
            alt='logo'
          />
          React Samples
        </a>
        <div className='w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700'>
          <div className='p-6 space-y-4 md:space-y-6 sm:p-8'>
            <h1 className='text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white'>
              🤑🤑🤑 VIP 會員登入 🤑🤑🤑
            </h1>
            <form
              className='space-y-4 md:space-y-6'
              onSubmit={handleSubmit(onSubmit)}
            >
              <div>
                <label
                  htmlFor='email'
                  className='block mb-2 text-sm font-medium text-gray-900 dark:text-white'
                >
                  電子郵件
                </label>
                <input
                  id='email'
                  defaultValue='whalebro@gmail.com'
                  {...register('email', {
                    required: true,
                    pattern:
                      /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/,
                  })}
                  className={!errors.email ? normalInput : errorInput}
                  placeholder='name@company.com'
                />
                {errors.email && (
                  <p className='mt-2 text-sm text-red-600 dark:text-red-500'>
                    <span className='font-medium'>Oh, snapp!</span> Error Type:[
                    {errors.email.type}]
                  </p>
                )}
              </div>

              <div>
                <label
                  htmlFor='password'
                  className='block mb-2 text-sm font-medium text-gray-900 dark:text-white'
                >
                  密碼
                </label>
                <input
                  id='password'
                  type='password'
                  {...register('password', {
                    required: true,
                    maxLength: 10,
                    minLength: 3,
                  })}
                  placeholder='••••••••'
                  className={!errors.password ? normalInput : errorInput}
                />
                {errors.password && (
                  <p className='mt-2 text-sm text-red-600 dark:text-red-500'>
                    <span className='font-medium'>Oh, snapp!</span> Error Type:[
                    {errors.password.type}]
                  </p>
                )}
              </div>

              <button
                type='submit'
                className='w-full text-white bg-indigo-500 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800'
              >
                入坑
              </button>
            </form>
          </div>
        </div>
      </div>
    </section>
  )
}

// Home.getLayout = function getLayout(page) {
//   return <Layout>{page}</Layout>
// }
